### ISSUE TITLE
Error on GET and POST javascript

### ISSUE THREAD

**Issue by godoymario95** [celsiusnarhwal/rest-against-humanity#1]
Hello, 

I was testing the api that you have created for your own project and I have seen that it does not return anything if the request is made by javascript, since it works by postman, investigating a little I have seen that it is possible that the configuration is in strict mode of the server.

Attached screenshots.

Thanks a lot 😊.

![Captura de pantalla 2022-08-08 123609](https://user-images.githubusercontent.com/14913357/183399947-fc94d98e-59aa-4128-9249-dbe6d355a701.png)
![Captura de pantalla 2022-08-08 123639](https://user-images.githubusercontent.com/14913357/183399950-fcbded1e-cf61-489a-99b0-e7b43aa0dc72.png)

**Comment by celsiusnarhwal** [comment]
I've updated the API to allow Cross-Origin Resource Sharing. Please try sending another request and get back to me with the results.

**Comment by godoymario95** [comment]
Thanks, its work now ☕👌

**Comment by abdelhalimjean** [comment]
can you revisit this after migrating to www.restagainsthumanity.com, i get the same issue as well now
